name: NdNoor786

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "hell"

          replace: "flame"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Stuffs'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: MdNoor786

          commit_user_email: haabhau2@gmail.com
